# Site settings
title: Shingwa Six的程式库
email:
description: > # this means to ignore newlines until "baseurl:"
  洗洗睡.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.waaile.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  shingwasix
duoshuo_short_name: shingwasix
duoshuo_thread_key_suffix: _a

# Build settings
markdown: kramdown
permalink: /:title