# Site settings
title: Shingwa Six的程式库
email:
description: > # this means to ignore newlines until "baseurl:"
  洗洗睡.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.waaile.com" # the base hostname & protocol for your site
enforce_ssl: blog.waaile.com
twitter_username: 
github_username:  shingwasix
duoshuo_short_name: shingwasix
disqus_url: waaile-blog.disqus.com
timezone: Asia/Chongqing
google_analytics: UA-42460321-1

# Build settings
markdown: kramdown
permalink: /:title
exclude: ["/bower_components/twemoji/assets"]