# Site settings
title: Shingwa Six的程式库
email:
description: > # this means to ignore newlines until "baseurl:"
  洗洗睡
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shingwasix.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  shingwasix
duoshuo_short_name: shingwasix
disqus_url: shingwasix.disqus.com
timezone: Asia/Chongqing
google_analytics_id: UA-75816296-1
cnzz_id: 4157597

# Build settings
markdown: kramdown
permalink: /:title
exclude: ["/bower_components/twemoji/assets"]